### ISSUE TITLE
unable to share files from my mac to phone in the get mode

### ISSUE THREAD

**Issue by shreyaspai77** [thevindu-w/clip_share_client#14] opened 2024-09-11 19:37 UTC
As suggested by the title, whenever i copy something on my mac and then click on the get file on my phone, it gives this toast telling Failed Getting Files, is this an issue only for me or is this something that has yet to be worked on?  It works fine on raycast somehow but not when i use cmd + copy on the file itself. 
![Screenshot_20240912-010644_ClipShare](https://github.com/user-attachments/assets/c9c9659d-f8b0-4db0-9fe0-b149cad9c036)

**Comment by thevindu-w** [comment] 2024-09-12 04:48
Please specify the server and client versions. I will try to recreate this issue with those versions.
Does your mac has Apple silicon or is it Intel?

**Comment by shreyaspai77** [comment] 2024-09-12 15:26
> Please specify the server and client versions. I will try to recreate this issue with those versions. Does your mac has Apple silicon or is it Intel?

i am using the latest version that is available for both the server and client, since i downloaded it last week. 
i have tried installing again and even then it doesn't work.
My mac is apple silicon,
Great app btw makes my life a lot easier 
Thank you

**Comment by thevindu-w** [comment] 2024-09-12 17:19
I checked the latest versions, but I couldn't recreate the issue. cmd+C and get files button works. I don't have raycast though. If that has a clipboard manager (or some similar functionality), I suspect it might interfere with the default clipboard functionality (cmd+C and other). I'll try to install raycast and see if this is the case. If you use any extensions of raycast (related to clipboard), can you please specify them? then I can create an almost identical environment to recreate the issue.

**Comment by shreyaspai77** [comment] 2024-09-14 06:56
> I checked the latest versions, but I couldn't recreate the issue. cmd+C and get files button works. I don't have raycast though. If that has a clipboard manager (or some similar functionality), I suspect it might interfere with the default clipboard functionality (cmd+C and other). I'll try to install raycast and see if this is the case. If you use any extensions of raycast (related to clipboard), can you please specify them? then I can create an almost identical environment to recreate the issue.

Raycast does have a clipboard manager (clipboard history) and thats about it I think. I'll try disabling it and let you know

**Comment by shreyaspai77** [comment] 2024-09-14 07:40
even without raycast it doesn't work, if it helps whenever i try to copy something using cmd+c, and click on get, it displays the filename on my phone, but when i click on file, it shows error getting files. 
I even reinstalled clipshare_server just in case i had any old version, but it doesn't work.

**Comment by thevindu-w** [comment] 2024-09-14 07:43
I think you have pressed the green GET button at the bottom **left** corner?
But you should press the green FILE button at the bottom **rignt** corner to get the **files**

**Comment by thevindu-w** [comment] 2024-09-14 07:48
Seems it has copied only the file name. That's why you get the file name but not the file. Can you try to copy the file by right clicking on the file, and try to get the file?. Also please check if Cmd+V works for pasting the copied file (on mac itself).
I'll try to provide a debug enabled version to view more details on what goes wrong.

**Comment by shreyaspai77** [comment] 2024-09-14 09:17
i have tried both right clicking to check if it makes it available for me on my phone , but it doesn't and cmd+c and cmd+v work perfectly on my system itself to copy files

**Comment by thevindu-w** [comment] 2024-09-14 09:36
Here is a debug version of clip_share, which prints more verbose output to the console. 
[clip_share-arm64-debug.zip](https://github.com/user-attachments/files/17001765/clip_share-arm64-debug.zip)
Unzip this and there is an clip_share executable file. Open a terminal at the folder where this clip_share file is available, and run it from the terminal with this command,
```bash
./clip_share
```
It will show some outputs in the terminal. Copy a file with cmd+C and try to get the file from mobile. Check if the program output in the terminal shows any output related to file paths and number of files copied.

**Comment by shreyaspai77** [comment] 2024-09-14 09:44
Connection: 192.168.1.2:39804
Client Common Name: clipshare_client
client verified
file:///.file/id=6571367.35494824
stat failed
Cleaning up resources before exit



is what it gives me when i try to send some file to my phone

**Comment by thevindu-w** [comment] 2024-09-14 09:51
is the actual path of the file you copied is  `/.file/id=6571367.35494824` ? If not, there's something wrong. But now I think I found where's the issue. So I can try to fix that soon

**Comment by shreyaspai77** [comment] 2024-09-14 10:02
the actual path of the file is /Users/shreyaspaiatkere/Downloads/IMG-20240906-WA0000.jpg 
but its showing file:///.file/id=6571367.49391166

i assume its macos's internal file reference.

**Comment by thevindu-w** [comment] 2024-09-14 10:03
Yes, I have to convert the file reference URL to path, which is currently not done. I'll fix that

**Comment by shreyaspai77** [comment] 2024-09-14 10:05
okay, thank you

**Comment by thevindu-w** [comment] 2024-09-14 11:57
I applied a fix for this issue, but since I couldn't reproduce the issue locally, I cannot verify if this actually fixes the problem. Here is a preview version of the fixed clip_share,
[clip_share_3.3.2-alpha.zip](https://github.com/user-attachments/files/17002184/clip_share_3.3.2-alpha.zip)
There are release and debug versions (with and without verbose console output). Please try the release version first, and if that works, the issue is solved. If that didn't work, please run the debug version in this to see what happens with the changes. Running either release or debug executable is same as before - i.e. open the terminal in the corresponding directory and run,
```bash
./clip_share
```

**Comment by shreyaspai77** [comment] 2024-09-14 14:33
i have tried this and now the cmd + c works perfectly for files even outside raycast. 
Thank you, also how do i make it so that this works everytime on startup.
can i just make a script that runs this on start-up? 
Also, theres a slight problem with images on the app, while it sends the image to my phone i get shown something like this, this again works fine in raycast for some reason, attached below are the screenshots
 ![Screenshot_20240914-195858_Material_Files (1)](https://github.com/user-attachments/assets/8273e257-7945-4530-bbb2-9229222c437d)
![Screenshot_20240914-195902_Photos](https://github.com/user-attachments/assets/a5aa86d3-6208-429d-a82b-3f309fc963ff)

# this is the actual image
--------------------------
<img width="783" alt="Screenshot 2024-09-14 at 5 15 38 PM" src="https://github.com/user-attachments/assets/973121aa-65bd-49e5-996d-f67b7ae9e82f">

**Comment by thevindu-w** [comment] 2024-09-14 14:42
> how do i make it so that this works everytime on startup.
> can i just make a script that runs this on start-up?

I will create a patch release with the fix, so that you can install the fixed version. As a temporary workaround, you may replace the file `/Users/<your username>/.local/bin/clip_share` with the fixed version (release/clip_share) I uploaded above, and reboot to apply the change. (I assume you have already installed the latest version 3.3.1 that had the bug. Installation is required to run on startup)

**Comment by thevindu-w** [comment] 2024-09-14 14:47
> Also, theres a slight problem with images on the app, while it sends the image to my phone i get shown something like this, this again works fine in raycast for some reason, attached below are the screenshots

Do you want to get that image **file** after copying it on mac? if so, then use the green **FILE** button as the image file is also a file. Then you will get it in ClipShareDocuments folder on your mobile (also accessible from the gallery app).
The IMAGE button is to get a screenshot or an image (not the png or jpg file).

**Comment by shreyaspai77** [comment] 2024-09-14 14:52
> > Also, theres a slight problem with images on the app, while it sends the image to my phone i get shown something like this, this again works fine in raycast for some reason, attached below are the screenshots
> 
> Do you want to get that image **file** after copying it on mac? if so, then use the green **FILE** button as the image file is also a file. Then you will get it in ClipShareDocuments folder on your mobile (also accessible from the gallery app). The IMAGE button is to get a screenshot or an image (not the png or jpg file).

okay thank you.

**Comment by shreyaspai77** [comment] 2024-09-14 14:53
> > how do i make it so that this works everytime on startup.
> > can i just make a script that runs this on start-up?
> 
> I will create a patch release with the fix, so that you can install the fixed version. As a temporary workaround, you may replace the file `/Users/<your username>/.local/bin/clip_share` with the fixed version (release/clip_share) I uploaded above, and reboot to apply the change. (I assume you have already installed the latest version 3.3.1 that had the bug. Installation is required to run on startup)

okay will do
Thank you

**Comment by thevindu-w** [comment] 2024-09-14 18:45
Created a new release including this bug fix at [github.com/thevindu-w/clip_share_server/releases/tag/v3.3.2](https://github.com/thevindu-w/clip_share_server/releases/tag/v3.3.2).
Since this bug is fixed, I will close this issue. If the new release still has the issue, please don't hesitate to reopen this issue.

**Closed by thevindu-w** 2024-09-14 18:45 UTC
